%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_NotPrepared
%% Source: /Users/david/Documents/workspace/my_otp/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_NotPrepared').
-ic_compiled("4_3_6").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/NotPrepared:1.0",
                   "NotPrepared",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/NotPrepared:1.0".

%% returns name
name() -> "CosTransactions_NotPrepared".



