%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_StructuredPushConsumer
%% Source: /Users/david/Documents/workspace/my_otp/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_STRUCTUREDPUSHCONSUMER_HRL).
-define(COSNOTIFYCOMM_STRUCTUREDPUSHCONSUMER_HRL, true).




-endif.


