%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_ProxyPushConsumer
%% Source: /Users/david/Documents/workspace/my_otp/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_PROXYPUSHCONSUMER_HRL).
-define(COSNOTIFYCHANNELADMIN_PROXYPUSHCONSUMER_HRL, true).




-endif.


