%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_PullConsumer
%% Source: /Users/david/Documents/workspace/my_otp/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_PULLCONSUMER_HRL).
-define(COSNOTIFYCOMM_PULLCONSUMER_HRL, true).




-endif.


