%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventComm_Event
%% Source: /Users/david/Documents/workspace/my_otp/lib/cosEvent/src/cosEventApp.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCOMM_EVENT_HRL).
-define(OE_COSEVENTCOMM_EVENT_HRL, true).




-endif.


