%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_cosEventApp
%% Source: /Users/david/Documents/workspace/my_otp/lib/cosEvent/src/cosEventApp.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTAPP_HRL).
-define(OE_COSEVENTAPP_HRL, true).




-endif.


