%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotificationComm
%% Source: /Users/david/Documents/workspace/my_otp/lib/cosNotification/src/cosNotificationAppComm.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFICATIONCOMM_HRL).
-define(OE_COSNOTIFICATIONCOMM_HRL, true).




-endif.


