%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_cos_naming
%% Source: /Users/david/Documents/workspace/my_otp/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COS_NAMING_HRL).
-define(OE_COS_NAMING_HRL, true).




-endif.


