%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_cos_naming_ext
%% Source: /Users/david/Documents/workspace/my_otp/lib/orber/COSS/CosNaming/cos_naming_ext.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COS_NAMING_EXT_HRL).
-define(OE_COS_NAMING_EXT_HRL, true).




-endif.


