%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PullConsumer
%% Source: /Users/david/Documents/workspace/my_otp/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PULLCONSUMER_HRL).
-define(COSEVENTCOMM_PULLCONSUMER_HRL, true).




-endif.


