%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_EventChannel
%% Source: /Users/david/Documents/workspace/my_otp/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_EVENTCHANNEL_HRL).
-define(COSEVENTCHANNELADMIN_EVENTCHANNEL_HRL, true).




-endif.


