%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventChannelAdmin
%% Source: /Users/david/Documents/workspace/my_otp/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCHANNELADMIN_HRL).
-define(OE_COSEVENTCHANNELADMIN_HRL, true).




-endif.


