%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime_TIO
%% Source: /Users/david/Documents/workspace/my_otp/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_TIO_HRL).
-define(COSTIME_TIO_HRL, true).




-endif.


