%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosFileTransfer
%% Source: /Users/david/Documents/workspace/my_otp/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSFILETRANSFER_HRL).
-define(OE_COSFILETRANSFER_HRL, true).




-endif.


