%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_Control
%% Source: /Users/david/Documents/workspace/my_otp/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_CONTROL_HRL).
-define(COSTRANSACTIONS_CONTROL_HRL, true).




-endif.


