%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosTransactions
%% Source: /Users/david/Documents/workspace/my_otp/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSTRANSACTIONS_HRL).
-define(OE_COSTRANSACTIONS_HRL, true).




-endif.


