%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosProperty
%% Source: /Users/david/Documents/workspace/my_otp/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSPROPERTY_HRL).
-define(OE_COSPROPERTY_HRL, true).




-endif.


