%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: OrberApp_IFR
%% Source: /Users/david/Documents/workspace/my_otp/lib/orber/src/OrberIFR.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ORBERAPP_IFR_HRL).
-define(ORBERAPP_IFR_HRL, true).




-endif.


