%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_stack
%% Source: /Users/david/Documents/workspace/my_otp/lib/orber/examples/Stack/stack.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_STACK_HRL).
-define(OE_STACK_HRL, true).




-endif.


