%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: StackModule_StackFactory
%% Source: /Users/david/Documents/workspace/my_otp/lib/orber/examples/Stack/stack.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(STACKMODULE_STACKFACTORY_HRL).
-define(STACKMODULE_STACKFACTORY_HRL, true).




-endif.


