/*
 *  Warning: Do not edit this file.  It was automatically
 *  generated by 'make_tables' on Sat Dec 23 13:08:43 2017.
 */

#ifndef __ERL_BIF_TABLE_H__
#define __ERL_BIF_TABLE_H__
typedef void *BifFunction;

typedef struct bif_entry {
    Eterm module;
    Eterm name;
    int arity;
    BifFunction f;
    BifFunction traced;
} BifEntry;

extern BifEntry bif_table[];
extern Export* bif_export[];

#define BIF_SIZE 484

#define BIF_abs_1 0
#define BIF_adler32_1 1
#define BIF_adler32_2 2
#define BIF_adler32_combine_3 3
#define BIF_apply_3 4
#define BIF_atom_to_list_1 5
#define BIF_binary_to_list_1 6
#define BIF_binary_to_list_3 7
#define BIF_binary_to_term_1 8
#define BIF_crc32_1 9
#define BIF_crc32_2 10
#define BIF_crc32_combine_3 11
#define BIF_date_0 12
#define BIF_delete_module_1 13
#define BIF_display_1 14
#define BIF_display_string_1 15
#define BIF_display_nl_0 16
#define BIF_element_2 17
#define BIF_erase_0 18
#define BIF_erase_1 19
#define BIF_exit_1 20
#define BIF_exit_2 21
#define BIF_external_size_1 22
#define BIF_external_size_2 23
#define BIF_float_1 24
#define BIF_float_to_list_1 25
#define BIF_float_to_list_2 26
#define BIF_fun_info_2 27
#define BIF_garbage_collect_0 28
#define BIF_get_0 29
#define BIF_get_1 30
#define BIF_get_keys_1 31
#define BIF_group_leader_0 32
#define BIF_group_leader_2 33
#define BIF_halt_0 34
#define BIF_halt_1 35
#define BIF_halt_2 36
#define BIF_phash_2 37
#define BIF_phash2_1 38
#define BIF_phash2_2 39
#define BIF_hd_1 40
#define BIF_integer_to_list_1 41
#define BIF_is_alive_0 42
#define BIF_length_1 43
#define BIF_link_1 44
#define BIF_list_to_atom_1 45
#define BIF_list_to_binary_1 46
#define BIF_list_to_float_1 47
#define BIF_list_to_integer_1 48
#define BIF_list_to_pid_1 49
#define BIF_list_to_tuple_1 50
#define BIF_loaded_0 51
#define BIF_localtime_0 52
#define BIF_localtime_to_universaltime_2 53
#define BIF_make_ref_0 54
#define BIF_md5_1 55
#define BIF_md5_init_0 56
#define BIF_md5_update_2 57
#define BIF_md5_final_1 58
#define BIF_module_loaded_1 59
#define BIF_function_exported_3 60
#define BIF_monitor_node_2 61
#define BIF_monitor_node_3 62
#define BIF_node_1 63
#define BIF_node_0 64
#define BIF_nodes_1 65
#define BIF_now_0 66
#define BIF_open_port_2 67
#define BIF_pid_to_list_1 68
#define BIF_ports_0 69
#define BIF_pre_loaded_0 70
#define BIF_process_flag_2 71
#define BIF_process_flag_3 72
#define BIF_process_info_1 73
#define BIF_process_info_2 74
#define BIF_processes_0 75
#define BIF_purge_module_1 76
#define BIF_put_2 77
#define BIF_register_2 78
#define BIF_registered_0 79
#define BIF_round_1 80
#define BIF_self_0 81
#define BIF_setelement_3 82
#define BIF_size_1 83
#define BIF_spawn_3 84
#define BIF_spawn_link_3 85
#define BIF_split_binary_2 86
#define BIF_statistics_1 87
#define BIF_term_to_binary_1 88
#define BIF_term_to_binary_2 89
#define BIF_throw_1 90
#define BIF_time_0 91
#define BIF_tl_1 92
#define BIF_trunc_1 93
#define BIF_tuple_to_list_1 94
#define BIF_universaltime_0 95
#define BIF_universaltime_to_localtime_1 96
#define BIF_unlink_1 97
#define BIF_unregister_1 98
#define BIF_whereis_1 99
#define BIF_spawn_opt_1 100
#define BIF_setnode_2 101
#define BIF_setnode_3 102
#define BIF_dist_exit_3 103
#define BIF_erts_internal_port_info_1 104
#define BIF_erts_internal_port_info_2 105
#define BIF_erts_internal_port_call_3 106
#define BIF_erts_internal_port_command_3 107
#define BIF_erts_internal_port_control_3 108
#define BIF_erts_internal_port_close_1 109
#define BIF_erts_internal_port_connect_2 110
#define BIF_erts_internal_request_system_task_3 111
#define BIF_erts_internal_check_process_code_2 112
#define BIF_erts_internal_map_to_tuple_keys_1 113
#define BIF_port_set_data_2 114
#define BIF_port_get_data_1 115
#define BIF_trace_pattern_2 116
#define BIF_trace_pattern_3 117
#define BIF_trace_3 118
#define BIF_trace_info_2 119
#define BIF_trace_delivered_1 120
#define BIF_seq_trace_2 121
#define BIF_seq_trace_info_1 122
#define BIF_seq_trace_print_1 123
#define BIF_seq_trace_print_2 124
#define BIF_suspend_process_2 125
#define BIF_resume_process_1 126
#define BIF_process_display_2 127
#define BIF_bump_reductions_1 128
#define BIF_math_cos_1 129
#define BIF_math_cosh_1 130
#define BIF_math_sin_1 131
#define BIF_math_sinh_1 132
#define BIF_math_tan_1 133
#define BIF_math_tanh_1 134
#define BIF_math_acos_1 135
#define BIF_math_acosh_1 136
#define BIF_math_asin_1 137
#define BIF_math_asinh_1 138
#define BIF_math_atan_1 139
#define BIF_math_atanh_1 140
#define BIF_math_erf_1 141
#define BIF_math_erfc_1 142
#define BIF_math_exp_1 143
#define BIF_math_log_1 144
#define BIF_math_log10_1 145
#define BIF_math_sqrt_1 146
#define BIF_math_atan2_2 147
#define BIF_math_pow_2 148
#define BIF_start_timer_3 149
#define BIF_send_after_3 150
#define BIF_cancel_timer_1 151
#define BIF_read_timer_1 152
#define BIF_make_tuple_2 153
#define BIF_append_element_2 154
#define BIF_make_tuple_3 155
#define BIF_system_flag_2 156
#define BIF_system_info_1 157
#define BIF_system_monitor_0 158
#define BIF_system_monitor_1 159
#define BIF_system_monitor_2 160
#define BIF_system_profile_2 161
#define BIF_system_profile_0 162
#define BIF_ref_to_list_1 163
#define BIF_port_to_list_1 164
#define BIF_fun_to_list_1 165
#define BIF_monitor_2 166
#define BIF_demonitor_1 167
#define BIF_demonitor_2 168
#define BIF_is_process_alive_1 169
#define BIF_error_1 170
#define BIF_error_2 171
#define BIF_raise_3 172
#define BIF_get_stacktrace_0 173
#define BIF_is_builtin_3 174
#define BIF_and_2 175
#define BIF_or_2 176
#define BIF_xor_2 177
#define BIF_not_1 178
#define BIF_sgt_2 179
#define BIF_sge_2 180
#define BIF_slt_2 181
#define BIF_sle_2 182
#define BIF_seq_2 183
#define BIF_seqeq_2 184
#define BIF_sneq_2 185
#define BIF_sneqeq_2 186
#define BIF_splus_2 187
#define BIF_sminus_2 188
#define BIF_stimes_2 189
#define BIF_div_2 190
#define BIF_intdiv_2 191
#define BIF_rem_2 192
#define BIF_bor_2 193
#define BIF_band_2 194
#define BIF_bxor_2 195
#define BIF_bsl_2 196
#define BIF_bsr_2 197
#define BIF_bnot_1 198
#define BIF_sminus_1 199
#define BIF_splus_1 200
#define BIF_ebif_bang_2 201
#define BIF_send_2 202
#define BIF_send_3 203
#define BIF_ebif_plusplus_2 204
#define BIF_append_2 205
#define BIF_ebif_minusminus_2 206
#define BIF_subtract_2 207
#define BIF_is_atom_1 208
#define BIF_is_list_1 209
#define BIF_is_tuple_1 210
#define BIF_is_float_1 211
#define BIF_is_integer_1 212
#define BIF_is_number_1 213
#define BIF_is_pid_1 214
#define BIF_is_port_1 215
#define BIF_is_reference_1 216
#define BIF_is_binary_1 217
#define BIF_is_function_1 218
#define BIF_is_function_2 219
#define BIF_is_record_2 220
#define BIF_is_record_3 221
#define BIF_match_spec_test_3 222
#define BIF_ets_all_0 223
#define BIF_ets_new_2 224
#define BIF_ets_delete_1 225
#define BIF_ets_delete_2 226
#define BIF_ets_delete_all_objects_1 227
#define BIF_ets_delete_object_2 228
#define BIF_ets_first_1 229
#define BIF_ets_is_compiled_ms_1 230
#define BIF_ets_lookup_2 231
#define BIF_ets_lookup_element_3 232
#define BIF_ets_info_1 233
#define BIF_ets_info_2 234
#define BIF_ets_last_1 235
#define BIF_ets_match_1 236
#define BIF_ets_match_2 237
#define BIF_ets_match_3 238
#define BIF_ets_match_object_1 239
#define BIF_ets_match_object_2 240
#define BIF_ets_match_object_3 241
#define BIF_ets_member_2 242
#define BIF_ets_next_2 243
#define BIF_ets_prev_2 244
#define BIF_ets_insert_2 245
#define BIF_ets_insert_new_2 246
#define BIF_ets_rename_2 247
#define BIF_ets_safe_fixtable_2 248
#define BIF_ets_slot_2 249
#define BIF_ets_update_counter_3 250
#define BIF_ets_select_1 251
#define BIF_ets_select_2 252
#define BIF_ets_select_3 253
#define BIF_ets_select_count_2 254
#define BIF_ets_select_reverse_1 255
#define BIF_ets_select_reverse_2 256
#define BIF_ets_select_reverse_3 257
#define BIF_ets_select_delete_2 258
#define BIF_ets_match_spec_compile_1 259
#define BIF_ets_match_spec_run_r_3 260
#define BIF_os_putenv_2 261
#define BIF_os_getenv_0 262
#define BIF_os_getenv_1 263
#define BIF_os_getpid_0 264
#define BIF_os_timestamp_0 265
#define BIF_erl_ddll_try_load_3 266
#define BIF_erl_ddll_try_unload_2 267
#define BIF_erl_ddll_loaded_drivers_0 268
#define BIF_erl_ddll_info_2 269
#define BIF_erl_ddll_format_error_int_1 270
#define BIF_erl_ddll_monitor_2 271
#define BIF_erl_ddll_demonitor_1 272
#define BIF_re_compile_1 273
#define BIF_re_compile_2 274
#define BIF_re_run_2 275
#define BIF_re_run_3 276
#define BIF_lists_member_2 277
#define BIF_lists_reverse_2 278
#define BIF_lists_keymember_3 279
#define BIF_lists_keysearch_3 280
#define BIF_lists_keyfind_3 281
#define BIF_erts_debug_disassemble_1 282
#define BIF_erts_debug_breakpoint_2 283
#define BIF_erts_debug_same_2 284
#define BIF_erts_debug_flat_size_1 285
#define BIF_erts_debug_get_internal_state_1 286
#define BIF_erts_debug_set_internal_state_2 287
#define BIF_erts_debug_display_1 288
#define BIF_erts_debug_dist_ext_to_term_2 289
#define BIF_erts_debug_instructions_0 290
#define BIF_erts_debug_dump_monitors_1 291
#define BIF_erts_debug_dump_links_1 292
#define BIF_erts_debug_lock_counters_1 293
#define BIF_code_get_chunk_2 294
#define BIF_code_module_md5_1 295
#define BIF_code_make_stub_module_3 296
#define BIF_code_is_module_native_1 297
#define BIF_hibernate_3 298
#define BIF_error_logger_warning_map_0 299
#define BIF_get_module_info_1 300
#define BIF_get_module_info_2 301
#define BIF_is_boolean_1 302
#define BIF_string_to_integer_1 303
#define BIF_string_to_float_1 304
#define BIF_make_fun_3 305
#define BIF_iolist_size_1 306
#define BIF_iolist_to_binary_1 307
#define BIF_list_to_existing_atom_1 308
#define BIF_is_bitstring_1 309
#define BIF_tuple_size_1 310
#define BIF_byte_size_1 311
#define BIF_bit_size_1 312
#define BIF_list_to_bitstring_1 313
#define BIF_bitstring_to_list_1 314
#define BIF_ets_update_element_3 315
#define BIF_decode_packet_3 316
#define BIF_unicode_characters_to_binary_2 317
#define BIF_unicode_characters_to_list_2 318
#define BIF_unicode_bin_is_7bit_1 319
#define BIF_atom_to_binary_2 320
#define BIF_binary_to_atom_2 321
#define BIF_binary_to_existing_atom_2 322
#define BIF_net_kernel_dflag_unicode_io_1 323
#define BIF_ets_give_away_3 324
#define BIF_ets_setopts_2 325
#define BIF_load_nif_2 326
#define BIF_call_on_load_function_1 327
#define BIF_finish_after_on_load_2 328
#define BIF_binary_to_term_2 329
#define BIF_binary_part_2 330
#define BIF_binary_part_3 331
#define BIF_binary_compile_pattern_1 332
#define BIF_binary_match_2 333
#define BIF_binary_match_3 334
#define BIF_binary_matches_2 335
#define BIF_binary_matches_3 336
#define BIF_binary_longest_common_prefix_1 337
#define BIF_binary_longest_common_suffix_1 338
#define BIF_binary_first_1 339
#define BIF_binary_last_1 340
#define BIF_binary_at_2 341
#define BIF_binary_binary_part_2 342
#define BIF_binary_binary_part_3 343
#define BIF_binary_bin_to_list_1 344
#define BIF_binary_bin_to_list_2 345
#define BIF_binary_bin_to_list_3 346
#define BIF_binary_list_to_bin_1 347
#define BIF_binary_copy_1 348
#define BIF_binary_copy_2 349
#define BIF_binary_referenced_byte_size_1 350
#define BIF_binary_encode_unsigned_1 351
#define BIF_binary_encode_unsigned_2 352
#define BIF_binary_decode_unsigned_1 353
#define BIF_binary_decode_unsigned_2 354
#define BIF_nif_error_1 355
#define BIF_nif_error_2 356
#define BIF_prim_file_internal_name2native_1 357
#define BIF_prim_file_internal_native2name_1 358
#define BIF_prim_file_internal_normalize_utf8_1 359
#define BIF_prim_file_is_translatable_1 360
#define BIF_file_native_name_encoding_0 361
#define BIF_check_old_code_1 362
#define BIF_universaltime_to_posixtime_1 363
#define BIF_posixtime_to_universaltime_1 364
#define BIF_dt_put_tag_1 365
#define BIF_dt_get_tag_0 366
#define BIF_dt_get_tag_data_0 367
#define BIF_dt_spread_tag_1 368
#define BIF_dt_restore_tag_1 369
#define BIF_dt_prepend_vm_tag_data_1 370
#define BIF_dt_append_vm_tag_data_1 371
#define BIF_prepare_loading_2 372
#define BIF_finish_loading_1 373
#define BIF_insert_element_3 374
#define BIF_delete_element_2 375
#define BIF_binary_to_integer_1 376
#define BIF_binary_to_integer_2 377
#define BIF_integer_to_binary_1 378
#define BIF_list_to_integer_2 379
#define BIF_float_to_binary_1 380
#define BIF_float_to_binary_2 381
#define BIF_binary_to_float_1 382
#define BIF_io_printable_range_0 383
#define BIF_os_unsetenv_1 384
#define BIF_re_inspect_2 385
#define BIF_is_map_1 386
#define BIF_map_size_1 387
#define BIF_maps_to_list_1 388
#define BIF_maps_find_2 389
#define BIF_maps_get_2 390
#define BIF_maps_from_list_1 391
#define BIF_maps_is_key_2 392
#define BIF_maps_keys_1 393
#define BIF_maps_merge_2 394
#define BIF_maps_new_0 395
#define BIF_maps_put_3 396
#define BIF_maps_remove_2 397
#define BIF_maps_update_3 398
#define BIF_maps_values_1 399
#define BIF_erts_internal_cmp_term_2 400
#define BIF_fun_info_mfa_1 401
#define BIF_hash_2 402
#define BIF_hipe_bifs_write_u8_2 403
#define BIF_hipe_bifs_write_u32_2 404
#define BIF_hipe_bifs_bytearray_2 405
#define BIF_hipe_bifs_bytearray_sub_2 406
#define BIF_hipe_bifs_bytearray_update_3 407
#define BIF_hipe_bifs_bitarray_2 408
#define BIF_hipe_bifs_bitarray_sub_2 409
#define BIF_hipe_bifs_bitarray_update_3 410
#define BIF_hipe_bifs_array_2 411
#define BIF_hipe_bifs_array_length_1 412
#define BIF_hipe_bifs_array_sub_2 413
#define BIF_hipe_bifs_array_update_3 414
#define BIF_hipe_bifs_ref_1 415
#define BIF_hipe_bifs_ref_get_1 416
#define BIF_hipe_bifs_ref_set_2 417
#define BIF_hipe_bifs_enter_code_2 418
#define BIF_hipe_bifs_alloc_data_2 419
#define BIF_hipe_bifs_constants_size_0 420
#define BIF_hipe_bifs_merge_term_1 421
#define BIF_hipe_bifs_fun_to_address_1 422
#define BIF_hipe_bifs_set_native_address_3 423
#define BIF_hipe_bifs_set_funinfo_native_address_3 424
#define BIF_hipe_bifs_invalidate_funinfo_native_addresses_1 425
#define BIF_hipe_bifs_update_code_size_3 426
#define BIF_hipe_bifs_code_size_1 427
#define BIF_hipe_bifs_enter_sdesc_1 428
#define BIF_hipe_bifs_bif_address_3 429
#define BIF_hipe_bifs_primop_address_1 430
#define BIF_hipe_bifs_atom_to_word_1 431
#define BIF_hipe_bifs_term_to_word_1 432
#define BIF_hipe_bifs_get_fe_2 433
#define BIF_hipe_bifs_set_native_address_in_fe_2 434
#define BIF_hipe_bifs_find_na_or_make_stub_2 435
#define BIF_hipe_bifs_check_crc_1 436
#define BIF_hipe_bifs_system_crc_1 437
#define BIF_hipe_bifs_get_rts_param_1 438
#define BIF_hipe_bifs_patch_insn_3 439
#define BIF_hipe_bifs_patch_call_3 440
#define BIF_hipe_bifs_add_ref_2 441
#define BIF_hipe_bifs_mark_referred_from_1 442
#define BIF_hipe_bifs_remove_refs_from_1 443
#define BIF_hipe_bifs_redirect_referred_from_1 444
#define BIF_hipe_bifs_call_count_on_1 445
#define BIF_hipe_bifs_call_count_off_1 446
#define BIF_hipe_bifs_call_count_get_1 447
#define BIF_hipe_bifs_call_count_clear_1 448
#define BIF_hipe_bifs_trap_count_get_0 449
#define BIF_hipe_bifs_trap_count_clear_0 450
#define BIF_hipe_bifs_process_info_0 451
#define BIF_hipe_bifs_process_info_clear_0 452
#define BIF_hipe_bifs_message_info_0 453
#define BIF_hipe_bifs_message_info_clear_0 454
#define BIF_hipe_bifs_message_sizes_0 455
#define BIF_hipe_bifs_gc_info_0 456
#define BIF_hipe_bifs_shared_gc_info_0 457
#define BIF_hipe_bifs_incremental_gc_info_0 458
#define BIF_hipe_bifs_gc_info_clear_0 459
#define BIF_hipe_bifs_pause_times_0 460
#define BIF_hipe_bifs_system_timer_0 461
#define BIF_hipe_bifs_system_timer_clear_0 462
#define BIF_hipe_bifs_send_timer_0 463
#define BIF_hipe_bifs_send_timer_clear_0 464
#define BIF_hipe_bifs_gc_timer_0 465
#define BIF_hipe_bifs_shared_gc_timer_0 466
#define BIF_hipe_bifs_gc_timer_clear_0 467
#define BIF_hipe_bifs_misc_timer_0 468
#define BIF_hipe_bifs_misc_timer_clear_0 469
#define BIF_hipe_bifs_get_hrvtime_0 470
#define BIF_hipe_bifs_stop_hrvtime_0 471
#define BIF_hipe_bifs_show_estack_1 472
#define BIF_hipe_bifs_show_heap_1 473
#define BIF_hipe_bifs_show_nstack_1 474
#define BIF_hipe_bifs_nstack_used_size_0 475
#define BIF_hipe_bifs_show_pcb_1 476
#define BIF_hipe_bifs_show_term_1 477
#define BIF_hipe_bifs_in_native_0 478
#define BIF_hipe_bifs_modeswitch_debug_on_0 479
#define BIF_hipe_bifs_modeswitch_debug_off_0 480
#define BIF_hipe_bifs_debug_native_called_2 481
#define BIF_hipe_bifs_llvm_fix_pinned_regs_0 482
#define BIF_hipe_bifs_write_u64_2 483

Eterm abs_1(Process*, Eterm*);
Eterm wrap_abs_1(Process*, Eterm*, UWord *I);
Eterm adler32_1(Process*, Eterm*);
Eterm wrap_adler32_1(Process*, Eterm*, UWord *I);
Eterm adler32_2(Process*, Eterm*);
Eterm wrap_adler32_2(Process*, Eterm*, UWord *I);
Eterm adler32_combine_3(Process*, Eterm*);
Eterm wrap_adler32_combine_3(Process*, Eterm*, UWord *I);
Eterm apply_3(Process*, Eterm*);
Eterm wrap_apply_3(Process*, Eterm*, UWord *I);
Eterm atom_to_list_1(Process*, Eterm*);
Eterm wrap_atom_to_list_1(Process*, Eterm*, UWord *I);
Eterm binary_to_list_1(Process*, Eterm*);
Eterm wrap_binary_to_list_1(Process*, Eterm*, UWord *I);
Eterm binary_to_list_3(Process*, Eterm*);
Eterm wrap_binary_to_list_3(Process*, Eterm*, UWord *I);
Eterm binary_to_term_1(Process*, Eterm*);
Eterm wrap_binary_to_term_1(Process*, Eterm*, UWord *I);
Eterm crc32_1(Process*, Eterm*);
Eterm wrap_crc32_1(Process*, Eterm*, UWord *I);
Eterm crc32_2(Process*, Eterm*);
Eterm wrap_crc32_2(Process*, Eterm*, UWord *I);
Eterm crc32_combine_3(Process*, Eterm*);
Eterm wrap_crc32_combine_3(Process*, Eterm*, UWord *I);
Eterm date_0(Process*, Eterm*);
Eterm wrap_date_0(Process*, Eterm*, UWord *I);
Eterm delete_module_1(Process*, Eterm*);
Eterm wrap_delete_module_1(Process*, Eterm*, UWord *I);
Eterm display_1(Process*, Eterm*);
Eterm wrap_display_1(Process*, Eterm*, UWord *I);
Eterm display_string_1(Process*, Eterm*);
Eterm wrap_display_string_1(Process*, Eterm*, UWord *I);
Eterm display_nl_0(Process*, Eterm*);
Eterm wrap_display_nl_0(Process*, Eterm*, UWord *I);
Eterm element_2(Process*, Eterm*);
Eterm wrap_element_2(Process*, Eterm*, UWord *I);
Eterm erase_0(Process*, Eterm*);
Eterm wrap_erase_0(Process*, Eterm*, UWord *I);
Eterm erase_1(Process*, Eterm*);
Eterm wrap_erase_1(Process*, Eterm*, UWord *I);
Eterm exit_1(Process*, Eterm*);
Eterm wrap_exit_1(Process*, Eterm*, UWord *I);
Eterm exit_2(Process*, Eterm*);
Eterm wrap_exit_2(Process*, Eterm*, UWord *I);
Eterm external_size_1(Process*, Eterm*);
Eterm wrap_external_size_1(Process*, Eterm*, UWord *I);
Eterm external_size_2(Process*, Eterm*);
Eterm wrap_external_size_2(Process*, Eterm*, UWord *I);
Eterm float_1(Process*, Eterm*);
Eterm wrap_float_1(Process*, Eterm*, UWord *I);
Eterm float_to_list_1(Process*, Eterm*);
Eterm wrap_float_to_list_1(Process*, Eterm*, UWord *I);
Eterm float_to_list_2(Process*, Eterm*);
Eterm wrap_float_to_list_2(Process*, Eterm*, UWord *I);
Eterm fun_info_2(Process*, Eterm*);
Eterm wrap_fun_info_2(Process*, Eterm*, UWord *I);
Eterm garbage_collect_0(Process*, Eterm*);
Eterm wrap_garbage_collect_0(Process*, Eterm*, UWord *I);
Eterm get_0(Process*, Eterm*);
Eterm wrap_get_0(Process*, Eterm*, UWord *I);
Eterm get_1(Process*, Eterm*);
Eterm wrap_get_1(Process*, Eterm*, UWord *I);
Eterm get_keys_1(Process*, Eterm*);
Eterm wrap_get_keys_1(Process*, Eterm*, UWord *I);
Eterm group_leader_0(Process*, Eterm*);
Eterm wrap_group_leader_0(Process*, Eterm*, UWord *I);
Eterm group_leader_2(Process*, Eterm*);
Eterm wrap_group_leader_2(Process*, Eterm*, UWord *I);
Eterm halt_0(Process*, Eterm*);
Eterm wrap_halt_0(Process*, Eterm*, UWord *I);
Eterm halt_1(Process*, Eterm*);
Eterm wrap_halt_1(Process*, Eterm*, UWord *I);
Eterm halt_2(Process*, Eterm*);
Eterm wrap_halt_2(Process*, Eterm*, UWord *I);
Eterm phash_2(Process*, Eterm*);
Eterm wrap_phash_2(Process*, Eterm*, UWord *I);
Eterm phash2_1(Process*, Eterm*);
Eterm wrap_phash2_1(Process*, Eterm*, UWord *I);
Eterm phash2_2(Process*, Eterm*);
Eterm wrap_phash2_2(Process*, Eterm*, UWord *I);
Eterm hd_1(Process*, Eterm*);
Eterm wrap_hd_1(Process*, Eterm*, UWord *I);
Eterm integer_to_list_1(Process*, Eterm*);
Eterm wrap_integer_to_list_1(Process*, Eterm*, UWord *I);
Eterm is_alive_0(Process*, Eterm*);
Eterm wrap_is_alive_0(Process*, Eterm*, UWord *I);
Eterm length_1(Process*, Eterm*);
Eterm wrap_length_1(Process*, Eterm*, UWord *I);
Eterm link_1(Process*, Eterm*);
Eterm wrap_link_1(Process*, Eterm*, UWord *I);
Eterm list_to_atom_1(Process*, Eterm*);
Eterm wrap_list_to_atom_1(Process*, Eterm*, UWord *I);
Eterm list_to_binary_1(Process*, Eterm*);
Eterm wrap_list_to_binary_1(Process*, Eterm*, UWord *I);
Eterm list_to_float_1(Process*, Eterm*);
Eterm wrap_list_to_float_1(Process*, Eterm*, UWord *I);
Eterm list_to_integer_1(Process*, Eterm*);
Eterm wrap_list_to_integer_1(Process*, Eterm*, UWord *I);
Eterm list_to_pid_1(Process*, Eterm*);
Eterm wrap_list_to_pid_1(Process*, Eterm*, UWord *I);
Eterm list_to_tuple_1(Process*, Eterm*);
Eterm wrap_list_to_tuple_1(Process*, Eterm*, UWord *I);
Eterm loaded_0(Process*, Eterm*);
Eterm wrap_loaded_0(Process*, Eterm*, UWord *I);
Eterm localtime_0(Process*, Eterm*);
Eterm wrap_localtime_0(Process*, Eterm*, UWord *I);
Eterm localtime_to_universaltime_2(Process*, Eterm*);
Eterm wrap_localtime_to_universaltime_2(Process*, Eterm*, UWord *I);
Eterm make_ref_0(Process*, Eterm*);
Eterm wrap_make_ref_0(Process*, Eterm*, UWord *I);
Eterm md5_1(Process*, Eterm*);
Eterm wrap_md5_1(Process*, Eterm*, UWord *I);
Eterm md5_init_0(Process*, Eterm*);
Eterm wrap_md5_init_0(Process*, Eterm*, UWord *I);
Eterm md5_update_2(Process*, Eterm*);
Eterm wrap_md5_update_2(Process*, Eterm*, UWord *I);
Eterm md5_final_1(Process*, Eterm*);
Eterm wrap_md5_final_1(Process*, Eterm*, UWord *I);
Eterm module_loaded_1(Process*, Eterm*);
Eterm wrap_module_loaded_1(Process*, Eterm*, UWord *I);
Eterm function_exported_3(Process*, Eterm*);
Eterm wrap_function_exported_3(Process*, Eterm*, UWord *I);
Eterm monitor_node_2(Process*, Eterm*);
Eterm wrap_monitor_node_2(Process*, Eterm*, UWord *I);
Eterm monitor_node_3(Process*, Eterm*);
Eterm wrap_monitor_node_3(Process*, Eterm*, UWord *I);
Eterm node_1(Process*, Eterm*);
Eterm wrap_node_1(Process*, Eterm*, UWord *I);
Eterm node_0(Process*, Eterm*);
Eterm wrap_node_0(Process*, Eterm*, UWord *I);
Eterm nodes_1(Process*, Eterm*);
Eterm wrap_nodes_1(Process*, Eterm*, UWord *I);
Eterm now_0(Process*, Eterm*);
Eterm wrap_now_0(Process*, Eterm*, UWord *I);
Eterm open_port_2(Process*, Eterm*);
Eterm wrap_open_port_2(Process*, Eterm*, UWord *I);
Eterm pid_to_list_1(Process*, Eterm*);
Eterm wrap_pid_to_list_1(Process*, Eterm*, UWord *I);
Eterm ports_0(Process*, Eterm*);
Eterm wrap_ports_0(Process*, Eterm*, UWord *I);
Eterm pre_loaded_0(Process*, Eterm*);
Eterm wrap_pre_loaded_0(Process*, Eterm*, UWord *I);
Eterm process_flag_2(Process*, Eterm*);
Eterm wrap_process_flag_2(Process*, Eterm*, UWord *I);
Eterm process_flag_3(Process*, Eterm*);
Eterm wrap_process_flag_3(Process*, Eterm*, UWord *I);
Eterm process_info_1(Process*, Eterm*);
Eterm wrap_process_info_1(Process*, Eterm*, UWord *I);
Eterm process_info_2(Process*, Eterm*);
Eterm wrap_process_info_2(Process*, Eterm*, UWord *I);
Eterm processes_0(Process*, Eterm*);
Eterm wrap_processes_0(Process*, Eterm*, UWord *I);
Eterm purge_module_1(Process*, Eterm*);
Eterm wrap_purge_module_1(Process*, Eterm*, UWord *I);
Eterm put_2(Process*, Eterm*);
Eterm wrap_put_2(Process*, Eterm*, UWord *I);
Eterm register_2(Process*, Eterm*);
Eterm wrap_register_2(Process*, Eterm*, UWord *I);
Eterm registered_0(Process*, Eterm*);
Eterm wrap_registered_0(Process*, Eterm*, UWord *I);
Eterm round_1(Process*, Eterm*);
Eterm wrap_round_1(Process*, Eterm*, UWord *I);
Eterm self_0(Process*, Eterm*);
Eterm wrap_self_0(Process*, Eterm*, UWord *I);
Eterm setelement_3(Process*, Eterm*);
Eterm wrap_setelement_3(Process*, Eterm*, UWord *I);
Eterm size_1(Process*, Eterm*);
Eterm wrap_size_1(Process*, Eterm*, UWord *I);
Eterm spawn_3(Process*, Eterm*);
Eterm wrap_spawn_3(Process*, Eterm*, UWord *I);
Eterm spawn_link_3(Process*, Eterm*);
Eterm wrap_spawn_link_3(Process*, Eterm*, UWord *I);
Eterm split_binary_2(Process*, Eterm*);
Eterm wrap_split_binary_2(Process*, Eterm*, UWord *I);
Eterm statistics_1(Process*, Eterm*);
Eterm wrap_statistics_1(Process*, Eterm*, UWord *I);
Eterm term_to_binary_1(Process*, Eterm*);
Eterm wrap_term_to_binary_1(Process*, Eterm*, UWord *I);
Eterm term_to_binary_2(Process*, Eterm*);
Eterm wrap_term_to_binary_2(Process*, Eterm*, UWord *I);
Eterm throw_1(Process*, Eterm*);
Eterm wrap_throw_1(Process*, Eterm*, UWord *I);
Eterm time_0(Process*, Eterm*);
Eterm wrap_time_0(Process*, Eterm*, UWord *I);
Eterm tl_1(Process*, Eterm*);
Eterm wrap_tl_1(Process*, Eterm*, UWord *I);
Eterm trunc_1(Process*, Eterm*);
Eterm wrap_trunc_1(Process*, Eterm*, UWord *I);
Eterm tuple_to_list_1(Process*, Eterm*);
Eterm wrap_tuple_to_list_1(Process*, Eterm*, UWord *I);
Eterm universaltime_0(Process*, Eterm*);
Eterm wrap_universaltime_0(Process*, Eterm*, UWord *I);
Eterm universaltime_to_localtime_1(Process*, Eterm*);
Eterm wrap_universaltime_to_localtime_1(Process*, Eterm*, UWord *I);
Eterm unlink_1(Process*, Eterm*);
Eterm wrap_unlink_1(Process*, Eterm*, UWord *I);
Eterm unregister_1(Process*, Eterm*);
Eterm wrap_unregister_1(Process*, Eterm*, UWord *I);
Eterm whereis_1(Process*, Eterm*);
Eterm wrap_whereis_1(Process*, Eterm*, UWord *I);
Eterm spawn_opt_1(Process*, Eterm*);
Eterm wrap_spawn_opt_1(Process*, Eterm*, UWord *I);
Eterm setnode_2(Process*, Eterm*);
Eterm wrap_setnode_2(Process*, Eterm*, UWord *I);
Eterm setnode_3(Process*, Eterm*);
Eterm wrap_setnode_3(Process*, Eterm*, UWord *I);
Eterm dist_exit_3(Process*, Eterm*);
Eterm wrap_dist_exit_3(Process*, Eterm*, UWord *I);
Eterm erts_internal_port_info_1(Process*, Eterm*);
Eterm wrap_erts_internal_port_info_1(Process*, Eterm*, UWord *I);
Eterm erts_internal_port_info_2(Process*, Eterm*);
Eterm wrap_erts_internal_port_info_2(Process*, Eterm*, UWord *I);
Eterm erts_internal_port_call_3(Process*, Eterm*);
Eterm wrap_erts_internal_port_call_3(Process*, Eterm*, UWord *I);
Eterm erts_internal_port_command_3(Process*, Eterm*);
Eterm wrap_erts_internal_port_command_3(Process*, Eterm*, UWord *I);
Eterm erts_internal_port_control_3(Process*, Eterm*);
Eterm wrap_erts_internal_port_control_3(Process*, Eterm*, UWord *I);
Eterm erts_internal_port_close_1(Process*, Eterm*);
Eterm wrap_erts_internal_port_close_1(Process*, Eterm*, UWord *I);
Eterm erts_internal_port_connect_2(Process*, Eterm*);
Eterm wrap_erts_internal_port_connect_2(Process*, Eterm*, UWord *I);
Eterm erts_internal_request_system_task_3(Process*, Eterm*);
Eterm wrap_erts_internal_request_system_task_3(Process*, Eterm*, UWord *I);
Eterm erts_internal_check_process_code_2(Process*, Eterm*);
Eterm wrap_erts_internal_check_process_code_2(Process*, Eterm*, UWord *I);
Eterm erts_internal_map_to_tuple_keys_1(Process*, Eterm*);
Eterm wrap_erts_internal_map_to_tuple_keys_1(Process*, Eterm*, UWord *I);
Eterm port_set_data_2(Process*, Eterm*);
Eterm wrap_port_set_data_2(Process*, Eterm*, UWord *I);
Eterm port_get_data_1(Process*, Eterm*);
Eterm wrap_port_get_data_1(Process*, Eterm*, UWord *I);
Eterm trace_pattern_2(Process*, Eterm*);
Eterm wrap_trace_pattern_2(Process*, Eterm*, UWord *I);
Eterm trace_pattern_3(Process*, Eterm*);
Eterm wrap_trace_pattern_3(Process*, Eterm*, UWord *I);
Eterm trace_3(Process*, Eterm*);
Eterm wrap_trace_3(Process*, Eterm*, UWord *I);
Eterm trace_info_2(Process*, Eterm*);
Eterm wrap_trace_info_2(Process*, Eterm*, UWord *I);
Eterm trace_delivered_1(Process*, Eterm*);
Eterm wrap_trace_delivered_1(Process*, Eterm*, UWord *I);
Eterm seq_trace_2(Process*, Eterm*);
Eterm wrap_seq_trace_2(Process*, Eterm*, UWord *I);
Eterm seq_trace_info_1(Process*, Eterm*);
Eterm wrap_seq_trace_info_1(Process*, Eterm*, UWord *I);
Eterm seq_trace_print_1(Process*, Eterm*);
Eterm wrap_seq_trace_print_1(Process*, Eterm*, UWord *I);
Eterm seq_trace_print_2(Process*, Eterm*);
Eterm wrap_seq_trace_print_2(Process*, Eterm*, UWord *I);
Eterm suspend_process_2(Process*, Eterm*);
Eterm wrap_suspend_process_2(Process*, Eterm*, UWord *I);
Eterm resume_process_1(Process*, Eterm*);
Eterm wrap_resume_process_1(Process*, Eterm*, UWord *I);
Eterm process_display_2(Process*, Eterm*);
Eterm wrap_process_display_2(Process*, Eterm*, UWord *I);
Eterm bump_reductions_1(Process*, Eterm*);
Eterm wrap_bump_reductions_1(Process*, Eterm*, UWord *I);
Eterm math_cos_1(Process*, Eterm*);
Eterm wrap_math_cos_1(Process*, Eterm*, UWord *I);
Eterm math_cosh_1(Process*, Eterm*);
Eterm wrap_math_cosh_1(Process*, Eterm*, UWord *I);
Eterm math_sin_1(Process*, Eterm*);
Eterm wrap_math_sin_1(Process*, Eterm*, UWord *I);
Eterm math_sinh_1(Process*, Eterm*);
Eterm wrap_math_sinh_1(Process*, Eterm*, UWord *I);
Eterm math_tan_1(Process*, Eterm*);
Eterm wrap_math_tan_1(Process*, Eterm*, UWord *I);
Eterm math_tanh_1(Process*, Eterm*);
Eterm wrap_math_tanh_1(Process*, Eterm*, UWord *I);
Eterm math_acos_1(Process*, Eterm*);
Eterm wrap_math_acos_1(Process*, Eterm*, UWord *I);
Eterm math_acosh_1(Process*, Eterm*);
Eterm wrap_math_acosh_1(Process*, Eterm*, UWord *I);
Eterm math_asin_1(Process*, Eterm*);
Eterm wrap_math_asin_1(Process*, Eterm*, UWord *I);
Eterm math_asinh_1(Process*, Eterm*);
Eterm wrap_math_asinh_1(Process*, Eterm*, UWord *I);
Eterm math_atan_1(Process*, Eterm*);
Eterm wrap_math_atan_1(Process*, Eterm*, UWord *I);
Eterm math_atanh_1(Process*, Eterm*);
Eterm wrap_math_atanh_1(Process*, Eterm*, UWord *I);
Eterm math_erf_1(Process*, Eterm*);
Eterm wrap_math_erf_1(Process*, Eterm*, UWord *I);
Eterm math_erfc_1(Process*, Eterm*);
Eterm wrap_math_erfc_1(Process*, Eterm*, UWord *I);
Eterm math_exp_1(Process*, Eterm*);
Eterm wrap_math_exp_1(Process*, Eterm*, UWord *I);
Eterm math_log_1(Process*, Eterm*);
Eterm wrap_math_log_1(Process*, Eterm*, UWord *I);
Eterm math_log10_1(Process*, Eterm*);
Eterm wrap_math_log10_1(Process*, Eterm*, UWord *I);
Eterm math_sqrt_1(Process*, Eterm*);
Eterm wrap_math_sqrt_1(Process*, Eterm*, UWord *I);
Eterm math_atan2_2(Process*, Eterm*);
Eterm wrap_math_atan2_2(Process*, Eterm*, UWord *I);
Eterm math_pow_2(Process*, Eterm*);
Eterm wrap_math_pow_2(Process*, Eterm*, UWord *I);
Eterm start_timer_3(Process*, Eterm*);
Eterm wrap_start_timer_3(Process*, Eterm*, UWord *I);
Eterm send_after_3(Process*, Eterm*);
Eterm wrap_send_after_3(Process*, Eterm*, UWord *I);
Eterm cancel_timer_1(Process*, Eterm*);
Eterm wrap_cancel_timer_1(Process*, Eterm*, UWord *I);
Eterm read_timer_1(Process*, Eterm*);
Eterm wrap_read_timer_1(Process*, Eterm*, UWord *I);
Eterm make_tuple_2(Process*, Eterm*);
Eterm wrap_make_tuple_2(Process*, Eterm*, UWord *I);
Eterm append_element_2(Process*, Eterm*);
Eterm wrap_append_element_2(Process*, Eterm*, UWord *I);
Eterm make_tuple_3(Process*, Eterm*);
Eterm wrap_make_tuple_3(Process*, Eterm*, UWord *I);
Eterm system_flag_2(Process*, Eterm*);
Eterm wrap_system_flag_2(Process*, Eterm*, UWord *I);
Eterm system_info_1(Process*, Eterm*);
Eterm wrap_system_info_1(Process*, Eterm*, UWord *I);
Eterm system_monitor_0(Process*, Eterm*);
Eterm wrap_system_monitor_0(Process*, Eterm*, UWord *I);
Eterm system_monitor_1(Process*, Eterm*);
Eterm wrap_system_monitor_1(Process*, Eterm*, UWord *I);
Eterm system_monitor_2(Process*, Eterm*);
Eterm wrap_system_monitor_2(Process*, Eterm*, UWord *I);
Eterm system_profile_2(Process*, Eterm*);
Eterm wrap_system_profile_2(Process*, Eterm*, UWord *I);
Eterm system_profile_0(Process*, Eterm*);
Eterm wrap_system_profile_0(Process*, Eterm*, UWord *I);
Eterm ref_to_list_1(Process*, Eterm*);
Eterm wrap_ref_to_list_1(Process*, Eterm*, UWord *I);
Eterm port_to_list_1(Process*, Eterm*);
Eterm wrap_port_to_list_1(Process*, Eterm*, UWord *I);
Eterm fun_to_list_1(Process*, Eterm*);
Eterm wrap_fun_to_list_1(Process*, Eterm*, UWord *I);
Eterm monitor_2(Process*, Eterm*);
Eterm wrap_monitor_2(Process*, Eterm*, UWord *I);
Eterm demonitor_1(Process*, Eterm*);
Eterm wrap_demonitor_1(Process*, Eterm*, UWord *I);
Eterm demonitor_2(Process*, Eterm*);
Eterm wrap_demonitor_2(Process*, Eterm*, UWord *I);
Eterm is_process_alive_1(Process*, Eterm*);
Eterm wrap_is_process_alive_1(Process*, Eterm*, UWord *I);
Eterm error_1(Process*, Eterm*);
Eterm wrap_error_1(Process*, Eterm*, UWord *I);
Eterm error_2(Process*, Eterm*);
Eterm wrap_error_2(Process*, Eterm*, UWord *I);
Eterm raise_3(Process*, Eterm*);
Eterm wrap_raise_3(Process*, Eterm*, UWord *I);
Eterm get_stacktrace_0(Process*, Eterm*);
Eterm wrap_get_stacktrace_0(Process*, Eterm*, UWord *I);
Eterm is_builtin_3(Process*, Eterm*);
Eterm wrap_is_builtin_3(Process*, Eterm*, UWord *I);
Eterm and_2(Process*, Eterm*);
Eterm wrap_and_2(Process*, Eterm*, UWord *I);
Eterm or_2(Process*, Eterm*);
Eterm wrap_or_2(Process*, Eterm*, UWord *I);
Eterm xor_2(Process*, Eterm*);
Eterm wrap_xor_2(Process*, Eterm*, UWord *I);
Eterm not_1(Process*, Eterm*);
Eterm wrap_not_1(Process*, Eterm*, UWord *I);
Eterm sgt_2(Process*, Eterm*);
Eterm wrap_sgt_2(Process*, Eterm*, UWord *I);
Eterm sge_2(Process*, Eterm*);
Eterm wrap_sge_2(Process*, Eterm*, UWord *I);
Eterm slt_2(Process*, Eterm*);
Eterm wrap_slt_2(Process*, Eterm*, UWord *I);
Eterm sle_2(Process*, Eterm*);
Eterm wrap_sle_2(Process*, Eterm*, UWord *I);
Eterm seq_2(Process*, Eterm*);
Eterm wrap_seq_2(Process*, Eterm*, UWord *I);
Eterm seqeq_2(Process*, Eterm*);
Eterm wrap_seqeq_2(Process*, Eterm*, UWord *I);
Eterm sneq_2(Process*, Eterm*);
Eterm wrap_sneq_2(Process*, Eterm*, UWord *I);
Eterm sneqeq_2(Process*, Eterm*);
Eterm wrap_sneqeq_2(Process*, Eterm*, UWord *I);
Eterm splus_2(Process*, Eterm*);
Eterm wrap_splus_2(Process*, Eterm*, UWord *I);
Eterm sminus_2(Process*, Eterm*);
Eterm wrap_sminus_2(Process*, Eterm*, UWord *I);
Eterm stimes_2(Process*, Eterm*);
Eterm wrap_stimes_2(Process*, Eterm*, UWord *I);
Eterm div_2(Process*, Eterm*);
Eterm wrap_div_2(Process*, Eterm*, UWord *I);
Eterm intdiv_2(Process*, Eterm*);
Eterm wrap_intdiv_2(Process*, Eterm*, UWord *I);
Eterm rem_2(Process*, Eterm*);
Eterm wrap_rem_2(Process*, Eterm*, UWord *I);
Eterm bor_2(Process*, Eterm*);
Eterm wrap_bor_2(Process*, Eterm*, UWord *I);
Eterm band_2(Process*, Eterm*);
Eterm wrap_band_2(Process*, Eterm*, UWord *I);
Eterm bxor_2(Process*, Eterm*);
Eterm wrap_bxor_2(Process*, Eterm*, UWord *I);
Eterm bsl_2(Process*, Eterm*);
Eterm wrap_bsl_2(Process*, Eterm*, UWord *I);
Eterm bsr_2(Process*, Eterm*);
Eterm wrap_bsr_2(Process*, Eterm*, UWord *I);
Eterm bnot_1(Process*, Eterm*);
Eterm wrap_bnot_1(Process*, Eterm*, UWord *I);
Eterm sminus_1(Process*, Eterm*);
Eterm wrap_sminus_1(Process*, Eterm*, UWord *I);
Eterm splus_1(Process*, Eterm*);
Eterm wrap_splus_1(Process*, Eterm*, UWord *I);
Eterm ebif_bang_2(Process*, Eterm*);
Eterm wrap_ebif_bang_2(Process*, Eterm*, UWord *I);
Eterm send_2(Process*, Eterm*);
Eterm wrap_send_2(Process*, Eterm*, UWord *I);
Eterm send_3(Process*, Eterm*);
Eterm wrap_send_3(Process*, Eterm*, UWord *I);
Eterm ebif_plusplus_2(Process*, Eterm*);
Eterm wrap_ebif_plusplus_2(Process*, Eterm*, UWord *I);
Eterm append_2(Process*, Eterm*);
Eterm wrap_append_2(Process*, Eterm*, UWord *I);
Eterm ebif_minusminus_2(Process*, Eterm*);
Eterm wrap_ebif_minusminus_2(Process*, Eterm*, UWord *I);
Eterm subtract_2(Process*, Eterm*);
Eterm wrap_subtract_2(Process*, Eterm*, UWord *I);
Eterm is_atom_1(Process*, Eterm*);
Eterm wrap_is_atom_1(Process*, Eterm*, UWord *I);
Eterm is_list_1(Process*, Eterm*);
Eterm wrap_is_list_1(Process*, Eterm*, UWord *I);
Eterm is_tuple_1(Process*, Eterm*);
Eterm wrap_is_tuple_1(Process*, Eterm*, UWord *I);
Eterm is_float_1(Process*, Eterm*);
Eterm wrap_is_float_1(Process*, Eterm*, UWord *I);
Eterm is_integer_1(Process*, Eterm*);
Eterm wrap_is_integer_1(Process*, Eterm*, UWord *I);
Eterm is_number_1(Process*, Eterm*);
Eterm wrap_is_number_1(Process*, Eterm*, UWord *I);
Eterm is_pid_1(Process*, Eterm*);
Eterm wrap_is_pid_1(Process*, Eterm*, UWord *I);
Eterm is_port_1(Process*, Eterm*);
Eterm wrap_is_port_1(Process*, Eterm*, UWord *I);
Eterm is_reference_1(Process*, Eterm*);
Eterm wrap_is_reference_1(Process*, Eterm*, UWord *I);
Eterm is_binary_1(Process*, Eterm*);
Eterm wrap_is_binary_1(Process*, Eterm*, UWord *I);
Eterm is_function_1(Process*, Eterm*);
Eterm wrap_is_function_1(Process*, Eterm*, UWord *I);
Eterm is_function_2(Process*, Eterm*);
Eterm wrap_is_function_2(Process*, Eterm*, UWord *I);
Eterm is_record_2(Process*, Eterm*);
Eterm wrap_is_record_2(Process*, Eterm*, UWord *I);
Eterm is_record_3(Process*, Eterm*);
Eterm wrap_is_record_3(Process*, Eterm*, UWord *I);
Eterm match_spec_test_3(Process*, Eterm*);
Eterm wrap_match_spec_test_3(Process*, Eterm*, UWord *I);
Eterm ets_all_0(Process*, Eterm*);
Eterm wrap_ets_all_0(Process*, Eterm*, UWord *I);
Eterm ets_new_2(Process*, Eterm*);
Eterm wrap_ets_new_2(Process*, Eterm*, UWord *I);
Eterm ets_delete_1(Process*, Eterm*);
Eterm wrap_ets_delete_1(Process*, Eterm*, UWord *I);
Eterm ets_delete_2(Process*, Eterm*);
Eterm wrap_ets_delete_2(Process*, Eterm*, UWord *I);
Eterm ets_delete_all_objects_1(Process*, Eterm*);
Eterm wrap_ets_delete_all_objects_1(Process*, Eterm*, UWord *I);
Eterm ets_delete_object_2(Process*, Eterm*);
Eterm wrap_ets_delete_object_2(Process*, Eterm*, UWord *I);
Eterm ets_first_1(Process*, Eterm*);
Eterm wrap_ets_first_1(Process*, Eterm*, UWord *I);
Eterm ets_is_compiled_ms_1(Process*, Eterm*);
Eterm wrap_ets_is_compiled_ms_1(Process*, Eterm*, UWord *I);
Eterm ets_lookup_2(Process*, Eterm*);
Eterm wrap_ets_lookup_2(Process*, Eterm*, UWord *I);
Eterm ets_lookup_element_3(Process*, Eterm*);
Eterm wrap_ets_lookup_element_3(Process*, Eterm*, UWord *I);
Eterm ets_info_1(Process*, Eterm*);
Eterm wrap_ets_info_1(Process*, Eterm*, UWord *I);
Eterm ets_info_2(Process*, Eterm*);
Eterm wrap_ets_info_2(Process*, Eterm*, UWord *I);
Eterm ets_last_1(Process*, Eterm*);
Eterm wrap_ets_last_1(Process*, Eterm*, UWord *I);
Eterm ets_match_1(Process*, Eterm*);
Eterm wrap_ets_match_1(Process*, Eterm*, UWord *I);
Eterm ets_match_2(Process*, Eterm*);
Eterm wrap_ets_match_2(Process*, Eterm*, UWord *I);
Eterm ets_match_3(Process*, Eterm*);
Eterm wrap_ets_match_3(Process*, Eterm*, UWord *I);
Eterm ets_match_object_1(Process*, Eterm*);
Eterm wrap_ets_match_object_1(Process*, Eterm*, UWord *I);
Eterm ets_match_object_2(Process*, Eterm*);
Eterm wrap_ets_match_object_2(Process*, Eterm*, UWord *I);
Eterm ets_match_object_3(Process*, Eterm*);
Eterm wrap_ets_match_object_3(Process*, Eterm*, UWord *I);
Eterm ets_member_2(Process*, Eterm*);
Eterm wrap_ets_member_2(Process*, Eterm*, UWord *I);
Eterm ets_next_2(Process*, Eterm*);
Eterm wrap_ets_next_2(Process*, Eterm*, UWord *I);
Eterm ets_prev_2(Process*, Eterm*);
Eterm wrap_ets_prev_2(Process*, Eterm*, UWord *I);
Eterm ets_insert_2(Process*, Eterm*);
Eterm wrap_ets_insert_2(Process*, Eterm*, UWord *I);
Eterm ets_insert_new_2(Process*, Eterm*);
Eterm wrap_ets_insert_new_2(Process*, Eterm*, UWord *I);
Eterm ets_rename_2(Process*, Eterm*);
Eterm wrap_ets_rename_2(Process*, Eterm*, UWord *I);
Eterm ets_safe_fixtable_2(Process*, Eterm*);
Eterm wrap_ets_safe_fixtable_2(Process*, Eterm*, UWord *I);
Eterm ets_slot_2(Process*, Eterm*);
Eterm wrap_ets_slot_2(Process*, Eterm*, UWord *I);
Eterm ets_update_counter_3(Process*, Eterm*);
Eterm wrap_ets_update_counter_3(Process*, Eterm*, UWord *I);
Eterm ets_select_1(Process*, Eterm*);
Eterm wrap_ets_select_1(Process*, Eterm*, UWord *I);
Eterm ets_select_2(Process*, Eterm*);
Eterm wrap_ets_select_2(Process*, Eterm*, UWord *I);
Eterm ets_select_3(Process*, Eterm*);
Eterm wrap_ets_select_3(Process*, Eterm*, UWord *I);
Eterm ets_select_count_2(Process*, Eterm*);
Eterm wrap_ets_select_count_2(Process*, Eterm*, UWord *I);
Eterm ets_select_reverse_1(Process*, Eterm*);
Eterm wrap_ets_select_reverse_1(Process*, Eterm*, UWord *I);
Eterm ets_select_reverse_2(Process*, Eterm*);
Eterm wrap_ets_select_reverse_2(Process*, Eterm*, UWord *I);
Eterm ets_select_reverse_3(Process*, Eterm*);
Eterm wrap_ets_select_reverse_3(Process*, Eterm*, UWord *I);
Eterm ets_select_delete_2(Process*, Eterm*);
Eterm wrap_ets_select_delete_2(Process*, Eterm*, UWord *I);
Eterm ets_match_spec_compile_1(Process*, Eterm*);
Eterm wrap_ets_match_spec_compile_1(Process*, Eterm*, UWord *I);
Eterm ets_match_spec_run_r_3(Process*, Eterm*);
Eterm wrap_ets_match_spec_run_r_3(Process*, Eterm*, UWord *I);
Eterm os_putenv_2(Process*, Eterm*);
Eterm wrap_os_putenv_2(Process*, Eterm*, UWord *I);
Eterm os_getenv_0(Process*, Eterm*);
Eterm wrap_os_getenv_0(Process*, Eterm*, UWord *I);
Eterm os_getenv_1(Process*, Eterm*);
Eterm wrap_os_getenv_1(Process*, Eterm*, UWord *I);
Eterm os_getpid_0(Process*, Eterm*);
Eterm wrap_os_getpid_0(Process*, Eterm*, UWord *I);
Eterm os_timestamp_0(Process*, Eterm*);
Eterm wrap_os_timestamp_0(Process*, Eterm*, UWord *I);
Eterm erl_ddll_try_load_3(Process*, Eterm*);
Eterm wrap_erl_ddll_try_load_3(Process*, Eterm*, UWord *I);
Eterm erl_ddll_try_unload_2(Process*, Eterm*);
Eterm wrap_erl_ddll_try_unload_2(Process*, Eterm*, UWord *I);
Eterm erl_ddll_loaded_drivers_0(Process*, Eterm*);
Eterm wrap_erl_ddll_loaded_drivers_0(Process*, Eterm*, UWord *I);
Eterm erl_ddll_info_2(Process*, Eterm*);
Eterm wrap_erl_ddll_info_2(Process*, Eterm*, UWord *I);
Eterm erl_ddll_format_error_int_1(Process*, Eterm*);
Eterm wrap_erl_ddll_format_error_int_1(Process*, Eterm*, UWord *I);
Eterm erl_ddll_monitor_2(Process*, Eterm*);
Eterm wrap_erl_ddll_monitor_2(Process*, Eterm*, UWord *I);
Eterm erl_ddll_demonitor_1(Process*, Eterm*);
Eterm wrap_erl_ddll_demonitor_1(Process*, Eterm*, UWord *I);
Eterm re_compile_1(Process*, Eterm*);
Eterm wrap_re_compile_1(Process*, Eterm*, UWord *I);
Eterm re_compile_2(Process*, Eterm*);
Eterm wrap_re_compile_2(Process*, Eterm*, UWord *I);
Eterm re_run_2(Process*, Eterm*);
Eterm wrap_re_run_2(Process*, Eterm*, UWord *I);
Eterm re_run_3(Process*, Eterm*);
Eterm wrap_re_run_3(Process*, Eterm*, UWord *I);
Eterm lists_member_2(Process*, Eterm*);
Eterm wrap_lists_member_2(Process*, Eterm*, UWord *I);
Eterm lists_reverse_2(Process*, Eterm*);
Eterm wrap_lists_reverse_2(Process*, Eterm*, UWord *I);
Eterm lists_keymember_3(Process*, Eterm*);
Eterm wrap_lists_keymember_3(Process*, Eterm*, UWord *I);
Eterm lists_keysearch_3(Process*, Eterm*);
Eterm wrap_lists_keysearch_3(Process*, Eterm*, UWord *I);
Eterm lists_keyfind_3(Process*, Eterm*);
Eterm wrap_lists_keyfind_3(Process*, Eterm*, UWord *I);
Eterm erts_debug_disassemble_1(Process*, Eterm*);
Eterm wrap_erts_debug_disassemble_1(Process*, Eterm*, UWord *I);
Eterm erts_debug_breakpoint_2(Process*, Eterm*);
Eterm wrap_erts_debug_breakpoint_2(Process*, Eterm*, UWord *I);
Eterm erts_debug_same_2(Process*, Eterm*);
Eterm wrap_erts_debug_same_2(Process*, Eterm*, UWord *I);
Eterm erts_debug_flat_size_1(Process*, Eterm*);
Eterm wrap_erts_debug_flat_size_1(Process*, Eterm*, UWord *I);
Eterm erts_debug_get_internal_state_1(Process*, Eterm*);
Eterm wrap_erts_debug_get_internal_state_1(Process*, Eterm*, UWord *I);
Eterm erts_debug_set_internal_state_2(Process*, Eterm*);
Eterm wrap_erts_debug_set_internal_state_2(Process*, Eterm*, UWord *I);
Eterm erts_debug_display_1(Process*, Eterm*);
Eterm wrap_erts_debug_display_1(Process*, Eterm*, UWord *I);
Eterm erts_debug_dist_ext_to_term_2(Process*, Eterm*);
Eterm wrap_erts_debug_dist_ext_to_term_2(Process*, Eterm*, UWord *I);
Eterm erts_debug_instructions_0(Process*, Eterm*);
Eterm wrap_erts_debug_instructions_0(Process*, Eterm*, UWord *I);
Eterm erts_debug_dump_monitors_1(Process*, Eterm*);
Eterm wrap_erts_debug_dump_monitors_1(Process*, Eterm*, UWord *I);
Eterm erts_debug_dump_links_1(Process*, Eterm*);
Eterm wrap_erts_debug_dump_links_1(Process*, Eterm*, UWord *I);
Eterm erts_debug_lock_counters_1(Process*, Eterm*);
Eterm wrap_erts_debug_lock_counters_1(Process*, Eterm*, UWord *I);
Eterm code_get_chunk_2(Process*, Eterm*);
Eterm wrap_code_get_chunk_2(Process*, Eterm*, UWord *I);
Eterm code_module_md5_1(Process*, Eterm*);
Eterm wrap_code_module_md5_1(Process*, Eterm*, UWord *I);
Eterm code_make_stub_module_3(Process*, Eterm*);
Eterm wrap_code_make_stub_module_3(Process*, Eterm*, UWord *I);
Eterm code_is_module_native_1(Process*, Eterm*);
Eterm wrap_code_is_module_native_1(Process*, Eterm*, UWord *I);
Eterm hibernate_3(Process*, Eterm*);
Eterm wrap_hibernate_3(Process*, Eterm*, UWord *I);
Eterm error_logger_warning_map_0(Process*, Eterm*);
Eterm wrap_error_logger_warning_map_0(Process*, Eterm*, UWord *I);
Eterm get_module_info_1(Process*, Eterm*);
Eterm wrap_get_module_info_1(Process*, Eterm*, UWord *I);
Eterm get_module_info_2(Process*, Eterm*);
Eterm wrap_get_module_info_2(Process*, Eterm*, UWord *I);
Eterm is_boolean_1(Process*, Eterm*);
Eterm wrap_is_boolean_1(Process*, Eterm*, UWord *I);
Eterm string_to_integer_1(Process*, Eterm*);
Eterm wrap_string_to_integer_1(Process*, Eterm*, UWord *I);
Eterm string_to_float_1(Process*, Eterm*);
Eterm wrap_string_to_float_1(Process*, Eterm*, UWord *I);
Eterm make_fun_3(Process*, Eterm*);
Eterm wrap_make_fun_3(Process*, Eterm*, UWord *I);
Eterm iolist_size_1(Process*, Eterm*);
Eterm wrap_iolist_size_1(Process*, Eterm*, UWord *I);
Eterm iolist_to_binary_1(Process*, Eterm*);
Eterm wrap_iolist_to_binary_1(Process*, Eterm*, UWord *I);
Eterm list_to_existing_atom_1(Process*, Eterm*);
Eterm wrap_list_to_existing_atom_1(Process*, Eterm*, UWord *I);
Eterm is_bitstring_1(Process*, Eterm*);
Eterm wrap_is_bitstring_1(Process*, Eterm*, UWord *I);
Eterm tuple_size_1(Process*, Eterm*);
Eterm wrap_tuple_size_1(Process*, Eterm*, UWord *I);
Eterm byte_size_1(Process*, Eterm*);
Eterm wrap_byte_size_1(Process*, Eterm*, UWord *I);
Eterm bit_size_1(Process*, Eterm*);
Eterm wrap_bit_size_1(Process*, Eterm*, UWord *I);
Eterm list_to_bitstring_1(Process*, Eterm*);
Eterm wrap_list_to_bitstring_1(Process*, Eterm*, UWord *I);
Eterm bitstring_to_list_1(Process*, Eterm*);
Eterm wrap_bitstring_to_list_1(Process*, Eterm*, UWord *I);
Eterm ets_update_element_3(Process*, Eterm*);
Eterm wrap_ets_update_element_3(Process*, Eterm*, UWord *I);
Eterm decode_packet_3(Process*, Eterm*);
Eterm wrap_decode_packet_3(Process*, Eterm*, UWord *I);
Eterm unicode_characters_to_binary_2(Process*, Eterm*);
Eterm wrap_unicode_characters_to_binary_2(Process*, Eterm*, UWord *I);
Eterm unicode_characters_to_list_2(Process*, Eterm*);
Eterm wrap_unicode_characters_to_list_2(Process*, Eterm*, UWord *I);
Eterm unicode_bin_is_7bit_1(Process*, Eterm*);
Eterm wrap_unicode_bin_is_7bit_1(Process*, Eterm*, UWord *I);
Eterm atom_to_binary_2(Process*, Eterm*);
Eterm wrap_atom_to_binary_2(Process*, Eterm*, UWord *I);
Eterm binary_to_atom_2(Process*, Eterm*);
Eterm wrap_binary_to_atom_2(Process*, Eterm*, UWord *I);
Eterm binary_to_existing_atom_2(Process*, Eterm*);
Eterm wrap_binary_to_existing_atom_2(Process*, Eterm*, UWord *I);
Eterm net_kernel_dflag_unicode_io_1(Process*, Eterm*);
Eterm wrap_net_kernel_dflag_unicode_io_1(Process*, Eterm*, UWord *I);
Eterm ets_give_away_3(Process*, Eterm*);
Eterm wrap_ets_give_away_3(Process*, Eterm*, UWord *I);
Eterm ets_setopts_2(Process*, Eterm*);
Eterm wrap_ets_setopts_2(Process*, Eterm*, UWord *I);
Eterm load_nif_2(Process*, Eterm*);
Eterm wrap_load_nif_2(Process*, Eterm*, UWord *I);
Eterm call_on_load_function_1(Process*, Eterm*);
Eterm wrap_call_on_load_function_1(Process*, Eterm*, UWord *I);
Eterm finish_after_on_load_2(Process*, Eterm*);
Eterm wrap_finish_after_on_load_2(Process*, Eterm*, UWord *I);
Eterm binary_to_term_2(Process*, Eterm*);
Eterm wrap_binary_to_term_2(Process*, Eterm*, UWord *I);
Eterm binary_part_2(Process*, Eterm*);
Eterm wrap_binary_part_2(Process*, Eterm*, UWord *I);
Eterm binary_part_3(Process*, Eterm*);
Eterm wrap_binary_part_3(Process*, Eterm*, UWord *I);
Eterm binary_compile_pattern_1(Process*, Eterm*);
Eterm wrap_binary_compile_pattern_1(Process*, Eterm*, UWord *I);
Eterm binary_match_2(Process*, Eterm*);
Eterm wrap_binary_match_2(Process*, Eterm*, UWord *I);
Eterm binary_match_3(Process*, Eterm*);
Eterm wrap_binary_match_3(Process*, Eterm*, UWord *I);
Eterm binary_matches_2(Process*, Eterm*);
Eterm wrap_binary_matches_2(Process*, Eterm*, UWord *I);
Eterm binary_matches_3(Process*, Eterm*);
Eterm wrap_binary_matches_3(Process*, Eterm*, UWord *I);
Eterm binary_longest_common_prefix_1(Process*, Eterm*);
Eterm wrap_binary_longest_common_prefix_1(Process*, Eterm*, UWord *I);
Eterm binary_longest_common_suffix_1(Process*, Eterm*);
Eterm wrap_binary_longest_common_suffix_1(Process*, Eterm*, UWord *I);
Eterm binary_first_1(Process*, Eterm*);
Eterm wrap_binary_first_1(Process*, Eterm*, UWord *I);
Eterm binary_last_1(Process*, Eterm*);
Eterm wrap_binary_last_1(Process*, Eterm*, UWord *I);
Eterm binary_at_2(Process*, Eterm*);
Eterm wrap_binary_at_2(Process*, Eterm*, UWord *I);
Eterm binary_binary_part_2(Process*, Eterm*);
Eterm wrap_binary_binary_part_2(Process*, Eterm*, UWord *I);
Eterm binary_binary_part_3(Process*, Eterm*);
Eterm wrap_binary_binary_part_3(Process*, Eterm*, UWord *I);
Eterm binary_bin_to_list_1(Process*, Eterm*);
Eterm wrap_binary_bin_to_list_1(Process*, Eterm*, UWord *I);
Eterm binary_bin_to_list_2(Process*, Eterm*);
Eterm wrap_binary_bin_to_list_2(Process*, Eterm*, UWord *I);
Eterm binary_bin_to_list_3(Process*, Eterm*);
Eterm wrap_binary_bin_to_list_3(Process*, Eterm*, UWord *I);
Eterm binary_list_to_bin_1(Process*, Eterm*);
Eterm wrap_binary_list_to_bin_1(Process*, Eterm*, UWord *I);
Eterm binary_copy_1(Process*, Eterm*);
Eterm wrap_binary_copy_1(Process*, Eterm*, UWord *I);
Eterm binary_copy_2(Process*, Eterm*);
Eterm wrap_binary_copy_2(Process*, Eterm*, UWord *I);
Eterm binary_referenced_byte_size_1(Process*, Eterm*);
Eterm wrap_binary_referenced_byte_size_1(Process*, Eterm*, UWord *I);
Eterm binary_encode_unsigned_1(Process*, Eterm*);
Eterm wrap_binary_encode_unsigned_1(Process*, Eterm*, UWord *I);
Eterm binary_encode_unsigned_2(Process*, Eterm*);
Eterm wrap_binary_encode_unsigned_2(Process*, Eterm*, UWord *I);
Eterm binary_decode_unsigned_1(Process*, Eterm*);
Eterm wrap_binary_decode_unsigned_1(Process*, Eterm*, UWord *I);
Eterm binary_decode_unsigned_2(Process*, Eterm*);
Eterm wrap_binary_decode_unsigned_2(Process*, Eterm*, UWord *I);
Eterm nif_error_1(Process*, Eterm*);
Eterm wrap_nif_error_1(Process*, Eterm*, UWord *I);
Eterm nif_error_2(Process*, Eterm*);
Eterm wrap_nif_error_2(Process*, Eterm*, UWord *I);
Eterm prim_file_internal_name2native_1(Process*, Eterm*);
Eterm wrap_prim_file_internal_name2native_1(Process*, Eterm*, UWord *I);
Eterm prim_file_internal_native2name_1(Process*, Eterm*);
Eterm wrap_prim_file_internal_native2name_1(Process*, Eterm*, UWord *I);
Eterm prim_file_internal_normalize_utf8_1(Process*, Eterm*);
Eterm wrap_prim_file_internal_normalize_utf8_1(Process*, Eterm*, UWord *I);
Eterm prim_file_is_translatable_1(Process*, Eterm*);
Eterm wrap_prim_file_is_translatable_1(Process*, Eterm*, UWord *I);
Eterm file_native_name_encoding_0(Process*, Eterm*);
Eterm wrap_file_native_name_encoding_0(Process*, Eterm*, UWord *I);
Eterm check_old_code_1(Process*, Eterm*);
Eterm wrap_check_old_code_1(Process*, Eterm*, UWord *I);
Eterm universaltime_to_posixtime_1(Process*, Eterm*);
Eterm wrap_universaltime_to_posixtime_1(Process*, Eterm*, UWord *I);
Eterm posixtime_to_universaltime_1(Process*, Eterm*);
Eterm wrap_posixtime_to_universaltime_1(Process*, Eterm*, UWord *I);
Eterm dt_put_tag_1(Process*, Eterm*);
Eterm wrap_dt_put_tag_1(Process*, Eterm*, UWord *I);
Eterm dt_get_tag_0(Process*, Eterm*);
Eterm wrap_dt_get_tag_0(Process*, Eterm*, UWord *I);
Eterm dt_get_tag_data_0(Process*, Eterm*);
Eterm wrap_dt_get_tag_data_0(Process*, Eterm*, UWord *I);
Eterm dt_spread_tag_1(Process*, Eterm*);
Eterm wrap_dt_spread_tag_1(Process*, Eterm*, UWord *I);
Eterm dt_restore_tag_1(Process*, Eterm*);
Eterm wrap_dt_restore_tag_1(Process*, Eterm*, UWord *I);
Eterm dt_prepend_vm_tag_data_1(Process*, Eterm*);
Eterm wrap_dt_prepend_vm_tag_data_1(Process*, Eterm*, UWord *I);
Eterm dt_append_vm_tag_data_1(Process*, Eterm*);
Eterm wrap_dt_append_vm_tag_data_1(Process*, Eterm*, UWord *I);
Eterm prepare_loading_2(Process*, Eterm*);
Eterm wrap_prepare_loading_2(Process*, Eterm*, UWord *I);
Eterm finish_loading_1(Process*, Eterm*);
Eterm wrap_finish_loading_1(Process*, Eterm*, UWord *I);
Eterm insert_element_3(Process*, Eterm*);
Eterm wrap_insert_element_3(Process*, Eterm*, UWord *I);
Eterm delete_element_2(Process*, Eterm*);
Eterm wrap_delete_element_2(Process*, Eterm*, UWord *I);
Eterm binary_to_integer_1(Process*, Eterm*);
Eterm wrap_binary_to_integer_1(Process*, Eterm*, UWord *I);
Eterm binary_to_integer_2(Process*, Eterm*);
Eterm wrap_binary_to_integer_2(Process*, Eterm*, UWord *I);
Eterm integer_to_binary_1(Process*, Eterm*);
Eterm wrap_integer_to_binary_1(Process*, Eterm*, UWord *I);
Eterm list_to_integer_2(Process*, Eterm*);
Eterm wrap_list_to_integer_2(Process*, Eterm*, UWord *I);
Eterm float_to_binary_1(Process*, Eterm*);
Eterm wrap_float_to_binary_1(Process*, Eterm*, UWord *I);
Eterm float_to_binary_2(Process*, Eterm*);
Eterm wrap_float_to_binary_2(Process*, Eterm*, UWord *I);
Eterm binary_to_float_1(Process*, Eterm*);
Eterm wrap_binary_to_float_1(Process*, Eterm*, UWord *I);
Eterm io_printable_range_0(Process*, Eterm*);
Eterm wrap_io_printable_range_0(Process*, Eterm*, UWord *I);
Eterm os_unsetenv_1(Process*, Eterm*);
Eterm wrap_os_unsetenv_1(Process*, Eterm*, UWord *I);
Eterm re_inspect_2(Process*, Eterm*);
Eterm wrap_re_inspect_2(Process*, Eterm*, UWord *I);
Eterm is_map_1(Process*, Eterm*);
Eterm wrap_is_map_1(Process*, Eterm*, UWord *I);
Eterm map_size_1(Process*, Eterm*);
Eterm wrap_map_size_1(Process*, Eterm*, UWord *I);
Eterm maps_to_list_1(Process*, Eterm*);
Eterm wrap_maps_to_list_1(Process*, Eterm*, UWord *I);
Eterm maps_find_2(Process*, Eterm*);
Eterm wrap_maps_find_2(Process*, Eterm*, UWord *I);
Eterm maps_get_2(Process*, Eterm*);
Eterm wrap_maps_get_2(Process*, Eterm*, UWord *I);
Eterm maps_from_list_1(Process*, Eterm*);
Eterm wrap_maps_from_list_1(Process*, Eterm*, UWord *I);
Eterm maps_is_key_2(Process*, Eterm*);
Eterm wrap_maps_is_key_2(Process*, Eterm*, UWord *I);
Eterm maps_keys_1(Process*, Eterm*);
Eterm wrap_maps_keys_1(Process*, Eterm*, UWord *I);
Eterm maps_merge_2(Process*, Eterm*);
Eterm wrap_maps_merge_2(Process*, Eterm*, UWord *I);
Eterm maps_new_0(Process*, Eterm*);
Eterm wrap_maps_new_0(Process*, Eterm*, UWord *I);
Eterm maps_put_3(Process*, Eterm*);
Eterm wrap_maps_put_3(Process*, Eterm*, UWord *I);
Eterm maps_remove_2(Process*, Eterm*);
Eterm wrap_maps_remove_2(Process*, Eterm*, UWord *I);
Eterm maps_update_3(Process*, Eterm*);
Eterm wrap_maps_update_3(Process*, Eterm*, UWord *I);
Eterm maps_values_1(Process*, Eterm*);
Eterm wrap_maps_values_1(Process*, Eterm*, UWord *I);
Eterm erts_internal_cmp_term_2(Process*, Eterm*);
Eterm wrap_erts_internal_cmp_term_2(Process*, Eterm*, UWord *I);
Eterm fun_info_mfa_1(Process*, Eterm*);
Eterm wrap_fun_info_mfa_1(Process*, Eterm*, UWord *I);
Eterm hash_2(Process*, Eterm*);
Eterm wrap_hash_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_write_u8_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_write_u8_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_write_u32_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_write_u32_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_bytearray_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_bytearray_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_bytearray_sub_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_bytearray_sub_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_bytearray_update_3(Process*, Eterm*);
Eterm wrap_hipe_bifs_bytearray_update_3(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_bitarray_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_bitarray_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_bitarray_sub_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_bitarray_sub_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_bitarray_update_3(Process*, Eterm*);
Eterm wrap_hipe_bifs_bitarray_update_3(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_array_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_array_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_array_length_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_array_length_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_array_sub_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_array_sub_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_array_update_3(Process*, Eterm*);
Eterm wrap_hipe_bifs_array_update_3(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_ref_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_ref_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_ref_get_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_ref_get_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_ref_set_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_ref_set_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_enter_code_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_enter_code_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_alloc_data_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_alloc_data_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_constants_size_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_constants_size_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_merge_term_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_merge_term_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_fun_to_address_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_fun_to_address_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_set_native_address_3(Process*, Eterm*);
Eterm wrap_hipe_bifs_set_native_address_3(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_set_funinfo_native_address_3(Process*, Eterm*);
Eterm wrap_hipe_bifs_set_funinfo_native_address_3(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_invalidate_funinfo_native_addresses_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_invalidate_funinfo_native_addresses_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_update_code_size_3(Process*, Eterm*);
Eterm wrap_hipe_bifs_update_code_size_3(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_code_size_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_code_size_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_enter_sdesc_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_enter_sdesc_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_bif_address_3(Process*, Eterm*);
Eterm wrap_hipe_bifs_bif_address_3(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_primop_address_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_primop_address_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_atom_to_word_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_atom_to_word_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_term_to_word_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_term_to_word_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_get_fe_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_get_fe_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_set_native_address_in_fe_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_set_native_address_in_fe_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_find_na_or_make_stub_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_find_na_or_make_stub_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_check_crc_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_check_crc_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_system_crc_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_system_crc_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_get_rts_param_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_get_rts_param_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_patch_insn_3(Process*, Eterm*);
Eterm wrap_hipe_bifs_patch_insn_3(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_patch_call_3(Process*, Eterm*);
Eterm wrap_hipe_bifs_patch_call_3(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_add_ref_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_add_ref_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_mark_referred_from_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_mark_referred_from_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_remove_refs_from_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_remove_refs_from_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_redirect_referred_from_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_redirect_referred_from_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_call_count_on_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_call_count_on_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_call_count_off_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_call_count_off_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_call_count_get_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_call_count_get_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_call_count_clear_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_call_count_clear_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_trap_count_get_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_trap_count_get_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_trap_count_clear_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_trap_count_clear_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_process_info_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_process_info_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_process_info_clear_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_process_info_clear_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_message_info_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_message_info_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_message_info_clear_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_message_info_clear_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_message_sizes_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_message_sizes_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_gc_info_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_gc_info_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_shared_gc_info_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_shared_gc_info_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_incremental_gc_info_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_incremental_gc_info_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_gc_info_clear_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_gc_info_clear_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_pause_times_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_pause_times_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_system_timer_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_system_timer_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_system_timer_clear_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_system_timer_clear_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_send_timer_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_send_timer_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_send_timer_clear_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_send_timer_clear_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_gc_timer_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_gc_timer_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_shared_gc_timer_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_shared_gc_timer_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_gc_timer_clear_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_gc_timer_clear_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_misc_timer_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_misc_timer_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_misc_timer_clear_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_misc_timer_clear_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_get_hrvtime_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_get_hrvtime_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_stop_hrvtime_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_stop_hrvtime_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_show_estack_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_show_estack_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_show_heap_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_show_heap_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_show_nstack_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_show_nstack_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_nstack_used_size_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_nstack_used_size_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_show_pcb_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_show_pcb_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_show_term_1(Process*, Eterm*);
Eterm wrap_hipe_bifs_show_term_1(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_in_native_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_in_native_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_modeswitch_debug_on_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_modeswitch_debug_on_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_modeswitch_debug_off_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_modeswitch_debug_off_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_debug_native_called_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_debug_native_called_2(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_llvm_fix_pinned_regs_0(Process*, Eterm*);
Eterm wrap_hipe_bifs_llvm_fix_pinned_regs_0(Process*, Eterm*, UWord *I);
Eterm hipe_bifs_write_u64_2(Process*, Eterm*);
Eterm wrap_hipe_bifs_write_u64_2(Process*, Eterm*, UWord *I);
#endif
